DEFINES+=PROJECT_CONF_H=\"project-conf.h\"

CONTIKI_PROJECT = auto-control-open-loop

CONTIKI_TARGET_SOURCEFILES += tsl256x.c

all: $(CONTIKI_PROJECT)

CONTIKI = ../../..
CONTIKI_WITH_RIME = 1
include $(CONTIKI)/Makefile.include
