all: dht11

CONTIKI=../../..

#CONTIKI_SOURCEFILES +=$(CONTIKI)/platform/cc2538dk/dev/DHT11.c
CONTIKI_TARGET_SOURCEFILES += DHT11-arch.c
CONTIKI_TARGET_SOURCEFILES += oled.c
include $(CONTIKI)/Makefile.include
