DEFINES+=PROJECT_CONF_H=\"project-conf.h\"

CONTIKI_PROJECT += test-motion

CONTIKI_TARGET_SOURCEFILES += motion-sensor.c

all: $(CONTIKI_PROJECT)

CONTIKI = ../../..
include $(CONTIKI)/Makefile.include
