DEFINES+=PROJECT_CONF_H=\"project-conf.h\"

CONTIKI_PROJECT: auto-control 

CONTIKI_TARGET_SOURCEFILES += tsl256x.c
CONTIKI_TARGET_SOURCEFILES += motion-sensor.c

all: $(CONTIKI_PROJECT)

CONTIKI = ../../..

include $(CONTIKI)/Makefile.include
